### ISSUE TITLE
Code seems to be broken

### ISSUE THREAD

**Issue by markg85** [ruudverheijden/p1-to-influxdb#1]
Hi,

Are you sure this project still works?
I'm getting 2 downright errors.

First one:
```
p1Reader.on('connected', portConfig => {
    console.log('Connection with the Smart Meter has been established on port: ' + portConfig.port
        + ' (BaudRate: ' + portConfig.baudRate + ', Parity: ' + portConfig.parity + ', Databits: '
        + portConfig.dataBits + 'Stopbits: ' + portConfig.stopBits + ')');
});
```
Here the `portConfig` seems to be an empty object for me.
I'm guessing all `portConfig` names need to change to `config.p1Reader`?

Second one:
```
    for (let i = 0; i < dataPoints.length; i++) {
        influxPoints.push({
            measurement: influxMeasurement,
            tags: {},
            fields: { 
                electricity_tarrif1: dataPoints[i].electricity_tarrif1,
                electricity_tarrif2: dataPoints[i].electricity_tarrif2,
                electricity_actual: dataPoints[i].electricity_actual,
                gas_reading: dataPoints[i].gas_reading
            },
            timestamp: new Date(dataPoints[i].timestamp)
        });
    }
```
`influxMeasurement` does not exist. I traced it back, you probably want to have `config.influxDb.measurementName` there.

Could you take a good look at the code again and breath some life into it?
I'd love to use it :)

Cheers,
Mark

**Comment by ruudverheijden** [comment]
Hi Mark,

Thanks! You're totally right.
I've fixed both errors. Hope everything works as expected now :)

Cheers,

Ruud
